# .streamlit/secrets.toml

BACKEND_URL = "https://reviving-the-indian-cow-breed-a.onrender.com/predict/"  # <-- PASTE YOUR RENDER URL HERE
GOOGLE_API_KEY = "AIzaSyB711m3ihs9Y09oqTnjy8a9QwpxR8DYK1I"         # <-- PASTE YOUR GOOGLE KEY HERE
